### ISSUE TITLE
FTDI device not listed in Raspberry PI3 in the initial screen

### ISSUE THREAD

**Issue by cvanand38** [Jark/FTDISample#10]
We are using Windows 10 IoT core on Rasberry PI3. We could successfully install the FTDI driver as outlined in the article. When we check driver status it says driver running. We compiled the sample application and downloaded to the PI3. But it doen't list the device. When we checked the code, the GetDevieList() function is returning 0 as device count.

What could be the problem ? Any idea ? Is this because we are using Pi3 while the sample is for Pi2 ?

**Comment by Jark** [comment]
Hi cvanand38, 

Unfortunately the installation procedure outlined in this repo has stopped working as of windows IOT version 10556.0. (see also the note on the readme and in the project description). The ftdi device should now be supported by Windows 10 IOT without having to install drivers.

See also issue #9.

To use the sample with the inbuilt drives see this comment: https://github.com/Jark/FTDISample/issues/9#issuecomment-183258116

Hope this helps you out. I might update the README.md to make it more obvious that the driver install does no longer work on newer version of the Windows 10 IOT firmware.

Jark

**Comment by cvanand38** [comment]
Hi Jark,

Thank you very much for your help ! The problem is resolved. We used the sample with the inbuilt drivers as suggested by you and it worked !

Have a nice day !

Best Regards
Anand

**Comment by Jark** [comment]
Hi Anand,

Great that you managed to get it to work :) 

Cheers,

Jark
