### ISSUE TITLE
Question: will also support the FT232RL? RS485 USB

### ISSUE THREAD

**Issue by ghost** [Jark/FTDISample#2]
Great! Do you think this driver will also support the FT232RL ( http://wiki.in-circuit.de/images/d/da/610000191A.pdf ) that I have already? I'm searching for the difference between drivers -- if any -- but don't see anything yet.

**Comment by Jark** [comment]
I don't see why not, looking at the page where I got the driver from: http://www.ftdichip.com/Drivers/D2XX.htm it doesn't look like it specifically excludes certain devices.

You might have to add the vid/pid for the FT232RL to this file though: https://github.com/Jark/FTDISample/blob/master/src/FTDISample/Package.appxmanifest 

Let me know how you get on.

**Comment by ghost** [comment]
Thanks. I'll try it!

**Comment by ghost** [comment]
Progress! The device is now active on the Windows IoT core precisely as your tutorial describes. Very nice.  Thanks again!

**Comment by Jark** [comment]
Glad that it was useful to you :) Hopefully eventually they'll make it work natively without having to use any different drivers or different apis.
