### ISSUE TITLE
Non MVVM example

### ISSUE THREAD

**Issue by rayd250592** [Jark/FTDISample#3]
Hi, 

Would you be able to provide a simple example that doesn't go along the MVVM design pattern?

Cheers!

**Comment by Jark** [comment]
Hi,

Unfortunately I don't have the time to add another simple example that doesn't use MVVM.

However, most of the FTDI library call logic can be found in https://github.com/Jark/FTDISample/blob/master/src/FTDISample/DeviceConnection.cs and is pretty self-explanatory.

I would be willing to accept a contribution to this repository if you want to contribute, https://github.com/Jark/FTDISample#setting-up-a-new-windows-universal-project-using-the-d2xx and the file above should get you started.

Any information of the ftdi driver lib can be found here: http://www.ftdichip.com/Support/Documents/InstallGuides/AN_271%20D2xx%20WinRT%20Guide.pdf

If there's any questions, feel free to ask.

Cheers,

Jark

**Comment by rayd250592** [comment]
Cheers! I've been experimenting with your work, and with the standard usb serial API in WIndows 10 IoT - but it's only your stuff that I can get to work :)

**Comment by Jark** [comment]
If you're using an FTDI usb-to-serial adapter then "my" stuff will be the only thing you can get to work since Windows 10 IoT doesn't support FTDI usb-to-serial adapters out of the box, hence the need to install the FTDI specific WinRT drivers :)

**Comment by djaus2** [comment]
Yes this is the only way to use FTDI usb-serial with Win 10 IoT at this stage. Given that FTDI is the basis of many things makes this methodology quite useful. There are other USB-Serial devices that do work with Win 10 IoT:out-of-the-box though:
- MS documents the [Silicon Labs CP2102 based USB-to-TTL module](http://ms-iot.github.io/content/en-US/win10/samples/SerialSample.htm#USB_TTL_Adapter) as working out-of-the-box
- I have also found that the [Freetronics USB- Serial](http://www.freetronics.com.au/collections/modules/products/usb-serial-adapter#.Vf5szjYVjmQ)  works OK out-of-the-box.
- The Windows Dev Center page ["Supported Peripheral Interfaces and Devices" page](http://ms-iot.github.io/content/en-US/win10/SupportedInterfaces.htm)
  also lists the Arduino Leonardo as USB-Serial compatible. meaning that if you take its micro USB and connect it to a RPI2 USB host port you get a serial port available on the RPI2. Whilst this does work for the Arduino Uno it only works in one direction for the Leonardo. You can write to the Leonardo from a RPI2 but can't read from it. Microsoft have acknowledged this bug.

Hope this helps.
