### ISSUE TITLE
Cannot find devices

### ISSUE THREAD

**Issue by hglenni** [Jark/FTDISample#7]
Sir,
 I have followed your steps, I get the information
 devcon status "USB\VID_0403&PID_6001"
 USB\VID_0403&PID_6001\PDVYRVLS
 Name: USB <-> Serial
 Driver is running.
 1 matching device(s) found.

But when I do the code, 
 var devList = ftManager.GetDeviceList(); 
 I get a empty list. Do you have any suggestions?

Thanks in advance

Glenn Inman

**Comment by Jark** [comment]
Hello Glenn,

Did you try/have a look at the sample? 

In there the app actually polls the `ftManager.GetDeviceList()` call since it takes a few seconds for the devices to be discovered by the driver. 

Hope this helps.

Jark.

**Comment by hglenni** [comment]
Dear sir,
Below is a excerpt from your app. This always returns 0. Perhaps I don’t understand
Below is an excerpt from the code that was in the zip file I download.

I am trying this, but still 0

```
            var deviceList = ftManager.GetDeviceList();
            int retry = 3;
            while(0 != retry--)
            {
                if(0 != deviceList.Count)
                {
                    break;
                }

                await Task.Delay(TimeSpan.FromSeconds(30));
                deviceList = ftManager.GetDeviceList();
            }


    private async void btnListDevices_Click(object sender, RoutedEventArgs e)
    {
        UInt32 id = 0;
        String s = "Testing Started " + DateTime.Now.ToString();
        AppendLogFile(s);
        AppendConsole(s);
        s = Environment.NewLine + "----------------------------------------";
        AppendLogFile(s);
        AppendConsole(s);

        var devList = ftManager.GetDeviceList();
        foreach (IFTDeviceInfoNode node in devList)
        {
            /*var dev = ftManager.OpenByDescription(node.Description);

            IChipId chipId = dev.ChipId;

            if (chipId != null)
            {
                id = await chipId.GetId();
            }*/

            // await OpenCloseTest(ftManager, node.DeviceId);
            await OpenCloseLoopbackTest(ftManager, node.DeviceId);
            // await LoopbackTest(ftManager, node.DeviceId);
            // await MultiThreadedReadWrite();
            // await QueueStatusTest(ftManager, node.DeviceId);
        }

        AppendLogFile(s);
        AppendConsole(s);
        s = "\r\nTesting Finished " + DateTime.Now.ToString() + "\r\n";
        AppendLogFile(s);
        AppendConsole(s);
    }
```

**Comment by Jark** [comment]
Hello Glenn,

I haven't put a zip up besides the "download ZIP" button offered on the github page (https://github.com/Jark/FTDISample). I suspect you downloaded the zip from FTDI's site since that doesn't look like my code.

The sample I'm talking about can be found in this repository in the src folder: (https://github.com/Jark/FTDISample/tree/master/src), please checkout the code of this repository and give that a try.

Jark

**Comment by hglenni** [comment]
You are correct, so yours is different, I will go there and look then

Thank you

**Comment by hglenni** [comment]
I have now downloaded your sample, it has run for about 10 min
I still get 0 devices. I placed a breakpoint on devices.add

Thanks

Glenn

```
    private void OnTick(object sender, object e)
    {
        var devicesList = ftManager.GetDeviceList();

        // add devices we don't have yet
        var devicesToAdd = devicesList.Where(x => Devices.All(y => y.DeviceId != x.DeviceId)).ToList();
        foreach (var device in devicesToAdd)
            Devices.Add(new DeviceNode(device));

        // remove any devices that are no longer connected
        var devicesToDelete = Devices.Where(x => devicesList.All(y => y.DeviceId != x.DeviceId)).ToList();
        foreach (var deviceNode in devicesToDelete)
            Devices.Remove(deviceNode);
    }
```

**Comment by hglenni** [comment]
Thanks for your help, it seems after a reboot (who knows why) I do now get devices.

Awesome for your assistance

**Comment by Jark** [comment]
No worries, it can take a bit of time to get this to work properly the first time.

Please note that microsoft is planning on working with FTDI to get the ftdi adapter to just work with the standard MS api's. See the msdn forums for more info: https://social.msdn.microsoft.com/Forums/en-US/682600bd-c0d3-4c12-9760-4b2f1c539f83/how-to-enable-a-usbtoserial-converter-on-raspberry-pi-2?forum=WindowsIoT#6ecb0ab1-7916-4579-9bb8-4a10e2d34edc
