### ISSUE TITLE
Hi Jark. please Help me.

### ISSUE THREAD

**Issue by kingkoz** [Jark/FTDISample#8]
i want C++  Example...

<C# code>
ftManager = new FTManager();
var devicesList = ftManager.GetDeviceList();

<C++ Code> (my thought....)
FTManager ^_ftmanager = ref new FTManager();
auto _myDevice = _ftmanager->GetDeviceList();

but.. _myDevice is "NULL"

um.. UWP C++/CX is very difficult..

you can Help me?

PLEASE!!!!!!!!!!!!!!!!!!!

**Comment by Jark** [comment]
Hey kingkoz,

Unfortunately I'm not that comfortable with C++ so I don't know if I can provide a sample in C++. Just to make sure you've configured the Raspberry PI 2 correctly:
- have you made sure to follow the steps on the [readme](https://github.com/Jark/FTDISample/blob/master/README.md) ?
- have you rebooted your device after restarting?
- you probably need to poll `_ftManager->GetDeviceList();` until you get a result.

Alternatively, I've heard that Raspberry PI 2 Windows IOT Build 10586 and Visual Studio 2015 SP 1 now support FTDI chipsets with the standard serial api's. It might be easier to use that to make it work now. This thread has more info: https://social.msdn.microsoft.com/Forums/en-US/682600bd-c0d3-4c12-9760-4b2f1c539f83/how-to-enable-a-usbtoserial-converter-on-raspberry-pi-2?forum=WindowsIoT. 

Hope this helps.

Jark

**Comment by kingkoz** [comment]
I want to use SerialDevice class.
https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.serialcommunication.serialdevice.aspx?f=255&MSPPError=-2147217396

impossible?

**Comment by Jark** [comment]
Have a read through the thread I linked above. It should now be possible to use the standard SerialDevice class.

The instructions on this repository is for the FTDI specific device driver, and requires manually installing the FTDI driver.
